spring.application.name=LibraryBack

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/DBLibrary
spring.datasource.username=postgres
spring.datasource.password=121212
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=zM3vX4i9KbD9X0tQbR6oPjXrN7vS8YlA1bF5LkE2gH9uJcQmWpRzT6xNvY8eDfGh
jwt.expiration=86400000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=horychanmey9@gmail.com
spring.mail.password=bjks szwk mhne gvvv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:5173